FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
COPY .env* ./
RUN npm ci
COPY . .
RUN npm run build

FROM pierrezemb/gostatic
COPY --from=builder /app/dist /srv/http
CMD ["-port","8080","-https-promote", "-enable-logging"]
